# Generated by Django 4.2.7 on 2023-12-02 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=300, null=True)),
                ('user_id', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('query', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=300, null=True)),
                ('user_id', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
