# Generated by Django 4.1.5 on 2023-12-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_alter_dataset_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='answer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
