# Generated by Django 4.1.5 on 2023-12-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_logs_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='response_time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
