# Generated by Django 4.1.5 on 2023-12-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_logs_response_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='user_id',
        ),
    ]
